### PR TITLE
Refactored repeated circuit/abstract code into single files

### PR DESCRIPTION
**Pull request by jrbeaumont**
@snowleopard: I have fixed the repeated code issues.

I had to create `Tuura.Concept.Circuit...` as I tried replacing the existing `Tuura.Concept.Circuit` and `Tuura.Concept.Abstract` but this causes issues with the simulation testing.

What do you think now?

### CODE REVIEW

**Comment by snowleopard** [comment]
Looks good! 

To avoid awkward `Circuit.Circuit`, perhaps, we could have `Circuit.Basic` (instead of `Circuit.Abstract`) and `Circuit.Derived` (instead of `Circuit.Circuit`)?

**Comment by jrbeaumont** [comment]
@snowleopard I have renamed those. They are better names. Thank you

**Comment by snowleopard** [comment]
Thanks! I have a feeling that we will still need to make some renaming to finally get it right, but for now let's go with this.

Shall I merge?

**Comment by jrbeaumont** [comment]
Not yet, there's issues with the testing that I have just fixed. Let's just confirm that the CI passes :)

I agree, some names need to be changed, but we can work this out while the tool works.

**Comment by jrbeaumont** [comment]
You can merge this now if you'd like :)

**Comment by jrbeaumont** [comment]
@snowleopard Can we merge this now?

**Comment by snowleopard** [comment]
@jrbeaumont Done!

**Pull request merged**
