### PR TITLE
Remove main, move examples to Tests.hs

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
This ticks off the first two TODOs in #9.

**Comment by snowleopard** [comment]
Travis fails?

**Comment by mvdan** [comment]
Uhhhh, one sec.

**Comment by mvdan** [comment]
Seems like a GHC 7.8 vs 7.10 issue. My 7.10 threw a warning about that import, but 7.8 seems to require it. Weird.

**Comment by mvdan** [comment]
@snowleopard see https://github.com/mvdan/concepts/commit/c7867785f9f359015f10472a03e5b70adf3f860b. Any ideas?

**Comment by mvdan** [comment]
I'll just remove it for now.

**Comment by snowleopard** [comment]
Let's give better names to C-element related tests: `testCElementGateLevel` and `testCElementProtocolLevel`. I prefer not to use contractions like `Proto` for functions that are not frequently used.

**Comment by mvdan** [comment]
@snowleopard done.

**Comment by snowleopard** [comment]
Great, thanks!

**Pull request merged**
