### PR TITLE
Cleanup and translate instructions

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by snowleopard** [comment]
Thanks @mvdan, merged!

@jrbeaumont Can you try the instructions?

**Comment by mvdan** [comment]
Of course this is the typical "works for me", so this is likely to not work for some random reason for @jrbeaumont. Feel free to ping me on slack if you get stuck.

**Comment by jrbeaumont** [comment]
I will give it a try now, see how it's works. 

Thanks @mvdan for sorting this out.

**Comment by jrbeaumont** [comment]
Your instructions work perfectly!

**Comment by jrbeaumont** [comment]
And the result is perfect!
Importing into Workcraft produces exactly what I expect.

**Comment by mvdan** [comment]
Cool!

See the TODOs in the source code though. I didn't have time to smooth some of the edges.

**Pull request merged**
