### PR TITLE
Added combinational gate concept

### PR DESCRIPTION
**Pull request by jrbeaumont**
The `combinationalGate` concept takes in a single Boolean function, the set function of a combinational gate. This type of gate uses this set function for both the set and reset of the gate, simply negating the set function for the reset. Therefore, this concept takes a single function, but produces a set and reset function for the given signal.

### CODE REVIEW

**Comment by snowleopard** [comment]
Something off with the CI?

**Review by snowleopard — COMMENTED** [review]
Looks fine but can you add a test?

**Comment by jrbeaumont** [comment]
The CI issue stems from a problem with not being able to find the stack file once it's downloaded. It should now be fixed.

**Comment by snowleopard** [comment]
@jrbeaumont Yep, your fix seems to work!

Now, let's add a test. For example, something like `combinationalGate (And x y) == andGate x y`.

**Comment by jrbeaumont** [comment]
@snowleopard I have added a test. It tests `combinationalGate` which uses `complexGate`, so this is also tested, and this in turn uses `function` so this is tested too!

**Comment by snowleopard** [comment]
@jrbeaumont Nice! The PR is now merged, thank you.

**Pull request merged**
