### PR TITLE
`BuckConverter` as module name in buck examples

### PR DESCRIPTION
**Pull request by jrbeaumont**

### CODE REVIEW

**Comment by snowleopard** [comment]
@jrbeaumont Thanks! I've merged this. Any changes required in the manual?

**Comment by jrbeaumont** [comment]
@snowleopard: We don't use these as an example in the manual. I have checked :)

**Comment by snowleopard** [comment]
Great! :) By the way, could we add a link to the manual from README?

**Comment by jrbeaumont** [comment]
To `doc/manual.md` or to the repo?

**Comment by snowleopard** [comment]
Yes, to `doc/manual.md`.

**Pull request merged**
